# ----------------------------------------------------------------------
# SERVER_METADATA: Built-in configuration for recognized server files
# ----------------------------------------------------------------------
SERVER_METADATA = {
    "Shuriken-US-CA.conf":  {"city": "Los Angeles", "state": "CA", "country": "US", "name": "Shuriken Los Angeles, CA, USA"}, # Not available
    "Shuriken-NL.conf":     {"city": "Amsterdam",   "state": "",   "country": "NL", "name": "Shuriken Amsterdam, Netherlands"}, # Not available
    "Shuriken-FL.conf":     {"city": "Miami",        "state": "FL", "country": "US", "name": "Shuriken Miami, FL, USA"}, # Not available
    "Shuriken-JA-TK.conf":  {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Shuriken Tokyo, Japan"}, # Not available
    "Shuriken-PA-PC.conf":  {"city": "Panama City",  "state": "",   "country": "PA", "name": "Shuriken Panama City, Panama"}, # Not available
    "Shuriken-CH-ZU.conf":  {"city": "Zurich",       "state": "",   "country": "CH", "name": "Shuriken Zurich, Switzerland"}, # Live
    "Shuriken-US-NY.conf":  {"city": "New York",     "state": "NY", "country": "US", "name": "Shuriken New York, NY, USA"}, # Not available
    "Shuriken-KL-MA.conf":  {"city": "KL",           "state": "",   "country": "MY", "name": "Shuriken KL, Malaysia"}, # Not available
    "Shuriken-IC.conf":     {"city": "",             "state": "",   "country": "IS", "name": "Shuriken Iceland"}, # Not available
    "wg-CA-FREE-1.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-1"},
    "wg-CA-FREE-2.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-2"},
    "wg-CA-FREE-3.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-3"},
    "wg-CA-FREE-4.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-4"},
    "wg-CA-FREE-5.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-5"},
    "wg-CA-FREE-6.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-6"},
    "wg-CA-FREE-7.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-7"},
    "wg-CA-FREE-8.conf":    {"city": "Toronto",      "state": "ON", "country": "CA", "name": "Toronto-8"},
    "wg-CA-FREE-13.conf":   {"city": "Vancouver",    "state": "BC", "country": "CA", "name": "Vancouver-13"},
    "wg-CH-FREE-4.conf":    {"city": "Zurich",       "state": "",   "country": "CH", "name": "Zurich-4"},
    "wg-CH-FREE-8.conf":    {"city": "Zurich",       "state": "",   "country": "CH", "name": "Zurich-8"},
    "wg-JP-FREE-3.conf":    {"city": "Osaka",        "state": "",   "country": "JP", "name": "Osaka-3"},
    "wg-JP-FREE-18.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-18"},
    "wg-JP-FREE-19.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-19"},
    "wg-JP-FREE-26.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-26"},
    "wg-JP-FREE-27.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-27"},
    "wg-JP-FREE-28.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-28"},
    "wg-JP-FREE-29.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-29"},
    "wg-JP-FREE-30.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-30"},
    "wg-JP-FREE-31.conf":   {"city": "Tokyo",        "state": "",   "country": "JP", "name": "Tokyo-31"},
    "wg-MX-FREE-4.conf":    {"city": "Mexico City",  "state": "",   "country": "MX", "name": "MX-4"},
    "wg-NL-FREE-2.conf":    {"city": "Amsterdam",    "state": "",   "country": "NL", "name": "Amsterdam-2"},
    "wg-NO-FREE-7.conf":    {"city": "Oslo",         "state": "",   "country": "NO", "name": "Oslo-7"},
    "wg-NO-FREE-8.conf":    {"city": "Oslo",         "state": "",   "country": "NO", "name": "Oslo-8"},
    "wg-NO-FREE-9.conf":    {"city": "Oslo",         "state": "",   "country": "NO", "name": "Oslo-9"},
    "wg-PL-FREE-2.conf":    {"city": "Warsaw",       "state": "",   "country": "PL", "name": "Warsaw-2"},
    "wg-PL-FREE-17.conf":   {"city": "Warsaw",       "state": "",   "country": "PL", "name": "Warsaw-17"},
    "wg-RO-FREE-21.conf":   {"city": "Bucharest",    "state": "",   "country": "RO", "name": "Bucharest-21"},
    "wg-RO-FREE-27.conf":   {"city": "Bucharest",    "state": "",   "country": "RO", "name": "Bucharest-27"},
    "wg-RO-FREE-28.conf":   {"city": "Bucharest",    "state": "",   "country": "RO", "name": "Bucharest-28"},
    "wg-SG-FREE-4.conf":    {"city": "Singapore",    "state": "",   "country": "SG", "name": "SG-4"},
    "wg-SG-FREE-7.conf":    {"city": "Singapore",    "state": "",   "country": "SG", "name": "SG-7"},
}

# ----------------------------------------------------------------------
# USER_SERVER_METADATA: Intended for a separate tab allowing user edits.
# ----------------------------------------------------------------------
_FREE_TIER_PREFIX = "wg-"
USER_SERVER_METADATA: dict = {
    k: v for k, v in SERVER_METADATA.items()
    if k.startswith(_FREE_TIER_PREFIX)
}

# ----------------------------------------------------------------------
# CITY_SYNONYMS
# ----------------------------------------------------------------------
CITY_SYNONYMS = {
    "amsterdam": ["am", "ams"],
    "bucharest": ["bu", "buc", "buch", "bucha", "buchar", "buchare", "buchares"],
    "los angeles": ["la"],
    "new york": ["nyc", "ny"],
    "osaka": ["osa", "osak"],           
    "oslo": ["osl"],                     
    "san diego": ["san"],
    "san jose": ["sj"],                
    "seattle": ["sea", "seat", "seatt", "seattl"],
    "tokyo": ["tok", "toky"],           
    "toronto": ["tor", "toro", "toron", "toront"],  
    "vancouver": ["van"],
    "warsaw": ["war", "wars", "warsa"],
    "zurich": ["zur"],
}

# ----------------------------------------------------------------------
# STATE_SYNONYMS — unchanged from original
# ----------------------------------------------------------------------
STATE_SYNONYMS = {
    # US States
    "alabama": ["al", "ala"],
    "alaska": ["ak"],
    "arizona": ["az", "ariz"],
    "arkansas": ["ar", "ark"],
    "california": ["ca", "calif", "cal", "cali"],
    "colorado": ["co", "colo", "col"],
    "connecticut": ["ct", "conn"],
    "delaware": ["de", "del"],
    "florida": ["fl", "fla"],
    "georgia": ["ga"],
    "hawaii": ["hi"],
    "idaho": ["id"],
    "illinois": ["il", "ill"],
    "indiana": ["in", "ind"],
    "iowa": ["ia"],
    "kansas": ["ks", "kan", "kans"],
    "kentucky": ["ky", "ken"],
    "louisiana": ["la"],
    "maine": ["me"],
    "maryland": ["md"],
    "massachusetts": ["ma", "mass"],
    "michigan": ["mi", "mich"],
    "minnesota": ["mn", "minn"],
    "mississippi": ["ms", "miss"],
    "missouri": ["mo"],
    "montana": ["mt", "mont"],
    "nebraska": ["ne", "nebr"],
    "nevada": ["nv", "nev"],
    "new hampshire": ["nh", "n h"],
    "new jersey": ["nj", "n j"],
    "new mexico": ["nm", "n mex"],
    "new york": ["ny", "n y"],
    "north carolina": ["nc", "n c"],
    "north dakota": ["nd", "n dak"],
    "ohio": ["oh"],
    "oklahoma": ["ok", "okla"],
    "oregon": ["or", "ore"],
    "pennsylvania": ["pa", "penn"],
    "rhode island": ["ri", "r i"],
    "south carolina": ["sc", "s c"],
    "south dakota": ["sd", "s dak"],
    "tennessee": ["tn", "tenn"],
    "texas": ["tx", "tex"],
    "utah": ["ut"],
    "vermont": ["vt"],
    "virginia": ["va"],
    "washington": ["wa", "wash", "washin", "washing", "washingt", "washingto"],
    "west virginia": ["wv", "w va", "w virg"],
    "wisconsin": ["wi", "wis", "wisc"],
    "wyoming": ["wy", "wyo"],
    # Canadian Provinces/Territories
    "alberta": ["ab", "alta"],
    "british columbia": ["bc", "b c"],
    "manitoba": ["mb", "man"],
    "new brunswick": ["nb", "n b"],
    "newfoundland and labrador": ["nl", "newfoundland", "labrador", "nf"],
    "nova scotia": ["ns", "n s"],
    "nunavut": ["nu"],
    "northwest territories": ["nt", "n w t"],
    "ontario": ["on", "ont"],
    "prince edward island": ["pe", "p e i"],
    "quebec": ["qc", "que"],
    "saskatchewan": ["sk", "sask"],
    "yukon": ["yt", "y t", "yukon territory"],
}

# ----------------------------------------------------------------------
# COUNTRY_SYNONYMS — unchanged from original
# ----------------------------------------------------------------------
COUNTRY_SYNONYMS = {
    "afghanistan": ["af"],
    "albania": ["al"],
    "algeria": ["dz"],
    "american samoa": ["as"],
    "andorra": ["ad"],
    "angola": ["ao"],
    "anguilla": ["ai"],
    "antarctica": ["aq"],
    "antigua and barbuda": ["ag"],
    "argentina": ["ar"],
    "armenia": ["am"],
    "aruba": ["aw"],
    "australia": ["au", "aussie"],
    "austria": ["at"],
    "azerbaijan": ["az"],
    "bahamas": ["bs"],
    "bahrain": ["bh"],
    "bangladesh": ["bd"],
    "barbados": ["bb"],
    "belarus": ["by"],
    "belgium": ["be"],
    "belize": ["bz"],
    "benin": ["bj"],
    "bermuda": ["bm"],
    "bhutan": ["bt"],
    "bolivia": ["bo"],
    "bosnia and herzegovina": ["ba"],
    "botswana": ["bw"],
    "bouvet island": ["bv"],
    "brazil": ["br"],
    "british indian ocean territory": ["io"],
    "brunei": ["bn"],
    "bulgaria": ["bg"],
    "burkina faso": ["bf"],
    "burundi": ["bi"],
    "cabo verde": ["cv"],
    "cape verde": ["cv"],
    "cambodia": ["kh"],
    "cameroon": ["cm"],
    "canada": ["ca"],
    "cayman islands": ["ky"],
    "central african republic": ["cf"],
    "chad": ["td"],
    "chile": ["cl"],
    "china": ["cn"],
    "christmas island": ["cx"],
    "cocos islands": ["cc"],
    "colombia": ["co"],
    "comoros": ["km"],
    "congo": ["cg"],
    "democratic republic of the congo": ["cd"],
    "dr congo": ["cd"],
    "cook islands": ["ck"],
    "costa rica": ["cr"],
    "croatia": ["hr"],
    "cuba": ["cu"],
    "curacao": ["cw"],
    "cyprus": ["cy"],
    "czechia": ["cz"],
    "czech republic": ["cz"],
    "denmark": ["dk"],
    "djibouti": ["dj"],
    "dominica": ["dm"],
    "dominican republic": ["do"],
    "ecuador": ["ec"],
    "egypt": ["eg"],
    "el salvador": ["sv"],
    "equatorial guinea": ["gq"],
    "eritrea": ["er"],
    "estonia": ["ee"],
    "eswatini": ["sz"],
    "swaziland": ["sz"],
    "ethiopia": ["et"],
    "falkland islands": ["fk"],
    "faroe islands": ["fo"],
    "fiji": ["fj"],
    "finland": ["fi"],
    "france": ["fr"],
    "french guiana": ["gf"],
    "french polynesia": ["pf"],
    "french southern territories": ["tf"],
    "gabon": ["ga"],
    "gambia": ["gm"],
    "georgia": ["ge"],
    "germany": ["de"],
    "ghana": ["gh"],
    "gibraltar": ["gi"],
    "great britain": ["gb"],
    "greece": ["gr"],
    "greenland": ["gl"],
    "grenada": ["gd"],
    "guadeloupe": ["gp"],
    "guam": ["gu"],
    "guatemala": ["gt"],
    "guernsey": ["gg"],
    "guinea": ["gn"],
    "guinea bissau": ["gw"],
    "guyana": ["gy"],
    "haiti": ["ht"],
    "heard island and mcdonald islands": ["hm"],
    "honduras": ["hn"],
    "hong kong": ["hk"],
    "hungary": ["hu"],
    "iceland": ["is"],
    "india": ["in"],
    "indonesia": ["id"],
    "iran": ["ir"],
    "iraq": ["iq"],
    "ireland": ["ie"],
    "isle of man": ["im"],
    "israel": ["il"],
    "italy": ["it"],
    "ivory coast": ["ci"],
    "cote d'ivoire": ["ci"],
    "jamaica": ["jm"],
    "japan": ["jp", "ja"],
    "jersey": ["je"],
    "jordan": ["jo"],
    "kazakhstan": ["kz"],
    "kenya": ["ke"],
    "kiribati": ["ki"],
    "korea": ["kr"],
    "south korea": ["kr"],
    "republic of korea": ["kr"],
    "north korea": ["kp"],
    "dprk": ["kp"],
    "kuwait": ["kw"],
    "kyrgyzstan": ["kg"],
    "laos": ["la"],
    "latvia": ["lv"],
    "lebanon": ["lb"],
    "lesotho": ["ls"],
    "liberia": ["lr"],
    "libya": ["ly"],
    "liechtenstein": ["li"],
    "lithuania": ["lt"],
    "luxembourg": ["lu"],
    "macao": ["mo"],
    "madagascar": ["mg"],
    "malawi": ["mw"],
    "malaysia": ["my"],
    "maldives": ["mv"],
    "mali": ["ml"],
    "malta": ["mt"],
    "marshall islands": ["mh"],
    "martinique": ["mq"],
    "mauritania": ["mr"],
    "mauritius": ["mu"],
    "mayotte": ["yt"],
    "mexico": ["mx", "m", "me", "mex", "mexi", "mexic"],
    "micronesia": ["fm"],
    "moldova": ["md"],
    "monaco": ["mc"],
    "mongolia": ["mn"],
    "montenegro": ["me"],
    "montserrat": ["ms"],
    "morocco": ["ma"],
    "mozambique": ["mz"],
    "myanmar": ["mm"],
    "burma": ["mm"],
    "namibia": ["na"],
    "nauru": ["nr"],
    "nepal": ["np"],
    "netherlands": ["nl", "ne", "net", "neth", "nethe", "nether", "netherl", "netherla", "netherlan", "netherland", "holland", "dutch"],
    "new caledonia": ["nc"],
    "new zealand": ["nz"],
    "nicaragua": ["ni"],
    "niger": ["ne"],
    "nigeria": ["ng"],
    "niue": ["nu"],
    "norfolk island": ["nf"],
    "northern mariana islands": ["mp"],
    "norway": ["no", "n", "nor", "norw", "norwa"],
    "oman": ["om"],
    "pakistan": ["pk"],
    "palau": ["pw"],
    "palestine": ["ps"],
    "panama": ["pa"],
    "papua new guinea": ["pg"],
    "paraguay": ["py"],
    "peru": ["pe"],
    "philippines": ["ph"],
    "pitcairn": ["pn"],
    "poland": ["pl", "p", "po", "pol", "pola", "polan"],
    "portugal": ["pt"],
    "puerto rico": ["pr"],
    "qatar": ["qa"],
    "reunion": ["re"],
    "romania": ["ro", "romani"],
    "russia": ["ru"],
    "russian federation": ["ru"],
    "rwanda": ["rw"],
    "saint barthelemy": ["bl"],
    "saint helena": ["sh"],
    "saint kitts and nevis": ["kn"],
    "saint lucia": ["lc"],
    "saint martin": ["mf"],
    "saint pierre and miquelon": ["pm"],
    "saint vincent and the grenadines": ["vc"],
    "samoa": ["ws"],
    "san marino": ["sm"],
    "sao tome and principe": ["st"],
    "saudi arabia": ["sa"],
    "senegal": ["sn"],
    "serbia": ["rs"],
    "seychelles": ["sc"],
    "sierra leone": ["sl"],
    "singapore": ["sg", "s", "si", "sin", "sing", "singa", "singap", "singapo", "singapor"],
    "sint maarten": ["sx"],
    "slovakia": ["sk"],
    "slovenia": ["si"],
    "solomon islands": ["sb"],
    "somalia": ["so"],
    "south africa": ["za"],
    "south georgia and the south sandwich islands": ["gs"],
    "south sudan": ["ss"],
    "spain": ["es"],
    "sri lanka": ["lk"],
    "sudan": ["sd"],
    "suriname": ["sr"],
    "svalbard and jan mayen": ["sj"],
    "sweden": ["se"],
    "switzerland": ["ch", "sw", "swi", "swit", "switz", "switze", "switzer", "switzerl", "switzerla", "switzerlan", "swiss"],
    "syria": ["sy"],
    "taiwan": ["tw"],
    "tajikistan": ["tj"],
    "tanzania": ["tz"],
    "thailand": ["th"],
    "timor leste": ["tl"],
    "east timor": ["tl"],
    "togo": ["tg"],
    "tokelau": ["tk"],
    "tonga": ["to"],
    "trinidad and tobago": ["tt"],
    "tunisia": ["tn"],
    "turkey": ["tr"],
    "turkmenistan": ["tm"],
    "turks and caicos islands": ["tc"],
    "tuvalu": ["tv"],
    "uganda": ["ug"],
    "ukraine": ["ua"],
    "united arab emirates": ["ae", "uae", "emirates"],
    "united kingdom": ["gb", "uk", "britain", "england"],
    "united states": ["us", "usa", "america", "united states of america"],
    "us virgin islands": ["vi"],
    "uruguay": ["uy"],
    "uzbekistan": ["uz"],
    "vanuatu": ["vu"],
    "vatican city": ["va"],
    "holy see": ["va"],
    "venezuela": ["ve"],
    "vietnam": ["vn"],
    "wallis and futuna": ["wf"],
    "western sahara": ["eh"],
    "yemen": ["ye"],
    "zambia": ["zm"],
    "zimbabwe": ["zw"],
}
